# Generated by Django 5.2.6 on 2025-10-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_payment_per_booking'),
        ),
    ]
